version: 3
networks:
  banco:
  web:
  fila:
volumes:
  dados:
services:
  db:
    image: postgres:9.6 
    volumes:
      # Volumes dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:./scripts
      - ./scripts/init.sql:/docker-entrypoint-init.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13 
    volumes:
      # Site
      - ./web:/usr/share/nginx/html
      # Configuração do Proxy Reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    environment: 
      - DB_NAME=email_sender
    volumes:
      # API
      - ./app:/app 
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
  worker:
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    networks:
      - fila
    depends_on:
      - queue
      - app
  queue:
    image: redis:3.2
    networks:
      - fila